artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data
  unzip_dir: artifacts/data_ingestion
  username: "your-kaggle-username"
  key: "your-secret-api-key"