artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data
  unzip_dir: artifacts/data_ingestion
  username: "your-kaggle-username"
  key: "your-secret-api-key"


model_trainer: 
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_ingestion/test
  test_data_path: artifacts/data_ingestion/train
  model_path: artifacts/model_trainer/model.pkl